export const events = [
    {
        id: 1,
        name: "Lễ hội Ẩm thực Sài Gòn 2024",
        date: "15/06/2024",
        time: "09:00 - 18:00",
        location: "Công viên Tao Đàn",
        participants: 1250,
        maxParticipants: 2000,
        status: "upcoming",
        description: "Lễ hội ẩm thực lớn nhất năm với hơn 100 gian hàng",
        image: "/driftveil_dancing.png",
        category: "Festival",
    },
    {
        id: 2,
        name: "Workshop Nấu Phở Truyền Thống",
        date: "20/06/2024",
        time: "14:00 - 17:00",
        location: "Phở Hòa Pasteur",
        participants: 25,
        maxParticipants: 30,
        status: "upcoming",
        description: "Học cách nấu phở từ đầu bếp chuyên nghiệp",
        image: "/pho-cooking-class.jpg",
        category: "Workshop",
    },
    {
        id: 3,
        name: "Đêm Ẩm thực Đường phố",
        date: "10/06/2024",
        time: "18:00 - 23:00",
        location: "Phố đi bộ Nguyễn Huệ",
        participants: 500,
        maxParticipants: 500,
        status: "completed",
        description: "Khám phá ẩm thực đường phố Sài Gòn",
        image: "/street-food-night.jpg",
        category: "Night Market",
    },
    {
        id: 4,
        name: "Hội thảo Ẩm thực Bền vững",
        date: "12/06/2024",
        time: "10:00 - 12:00",
        location: "Khách sạn Rex",
        participants: 85,
        maxParticipants: 100,
        status: "ongoing",
        description: "Thảo luận về xu hướng ẩm thực bền vững",
        image: "/sustainable-food-conference.jpg",
        category: "Conference",
    },
]
