export const categories = [
    { id: "all", label: "Tất cả", count: 12 },
    { id: "workshop", label: "Workshop", count: 5 },
    { id: "cooking-class", label: "Lớp nấu ăn", count: 4 },
    { id: "food-tour", label: "Tour ẩm thực", count: 3 },
]

export const events = [
    {
        id: 1,
        title: "Workshop: Làm Phở Bò Truyền Thống",
        category: "workshop",
        date: "15/01/2025",
        time: "14:00 - 17:00",
        location: "Phở Hòa Pasteur, Q.3",
        host: "Chef Minh Nguyễn",
        participants: 24,
        maxParticipants: 30,
        price: "500,000đ",
        image: "/img/pho-bowl.jpg",
        description: "Học cách nấu phở bò chính gốc từ chef có hơn 20 năm kinh nghiệm. Bao gồm nguyên liệu và dụng cụ.",
        rating: 4.9,
        level: "Trung cấp",
        isFeatured: true,
        isTrending: true,
    },
    {
        id: 2,
        title: "Lớp học: Bánh Mì Sài Gòn",
        category: "cooking-class",
        date: "18/01/2025",
        time: "09:00 - 12:00",
        location: "Bánh Mì Huỳnh Hoa, Q.1",
        host: "Chef Hoa Trần",
        participants: 18,
        maxParticipants: 20,
        price: "350,000đ",
        image: "/img/banh-mi-sandwich.jpg",
        description: "Khám phá bí quyết làm bánh mì Sài Gòn ngon với nhân đa dạng và bánh giòn tan.",
        rating: 4.8,
        level: "Cơ bản",
        isFeatured: true,
        isTrending: false,
    },
    {
        id: 3,
        title: "Tour Ẩm Thực: Chợ Bến Thành",
        category: "food-tour",
        date: "20/01/2025",
        time: "17:00 - 21:00",
        location: "Chợ Bến Thành, Q.1",
        host: "Guide Lan Phạm",
        participants: 12,
        maxParticipants: 15,
        price: "450,000đ",
        image: "/img/com-tam-rice.jpg",
        description: "Khám phá ẩm thực đường phố Sài Gòn với hướng dẫn viên địa phương. Thưởng thức 8+ món ăn.",
        rating: 5.0,
        level: "Tất cả",
        isFeatured: false,
        isTrending: true,
    },
    {
        id: 4,
        title: "Workshop: Bún Bò Huế Chuẩn Vị",
        category: "workshop",
        date: "22/01/2025",
        time: "10:00 - 13:00",
        location: "Bún Bò Huế 3A3, Q.10",
        host: "Chef Tuấn Lê",
        participants: 15,
        maxParticipants: 25,
        price: "480,000đ",
        image: "/img/bun-bo-hue.png",
        description: "Học cách nấu bún bò Huế với nước dùng đậm đà và cách chế biến các loại nhân.",
        rating: 4.7,
        level: "Trung cấp",
        isFeatured: false,
        isTrending: false,
    },
    {
        id: 5,
        title: "Lớp học: Cơm Tấm Sườn Bì Chả",
        category: "cooking-class",
        date: "25/01/2025",
        time: "15:00 - 18:00",
        location: "Cơm Tấm Mộc, Q.Bình Thạnh",
        host: "Chef Mộc Nguyễn",
        participants: 20,
        maxParticipants: 25,
        price: "400,000đ",
        image: "/img/com-tam-rice.jpg",
        description: "Khám phá bí quyết làm cơm tấm ngon với sườn nướng, bì và chả trứng đặc biệt.",
        rating: 4.6,
        level: "Cơ bản",
        isFeatured: false,
        isTrending: false,
    },
    {
        id: 6,
        title: "Tour Ẩm Thực: Quận 5 - Chợ Lớn",
        category: "food-tour",
        date: "28/01/2025",
        time: "18:00 - 22:00",
        location: "Quận 5, TP.HCM",
        host: "Guide Hùng Võ",
        participants: 8,
        maxParticipants: 12,
        price: "520,000đ",
        image: "/img/pho-bowl.jpg",
        description: "Khám phá ẩm thực Hoa - Việt tại Chợ Lớn với các món ăn đặc sắc và câu chuyện văn hóa.",
        rating: 4.9,
        level: "Tất cả",
        isFeatured: true,
        isTrending: true,
    },
]
