import { Flashcard, Language, ColorTheme } from "./types"

export const COLOR_THEMES: Record<string, ColorTheme> = {
  easy: {
    bg: "bg-gradient-to-br from-emerald-50 to-teal-50 dark:from-emerald-950/30 dark:to-teal-950/30",
    border: "border-emerald-200 dark:border-emerald-800",
    accent: "text-emerald-700 dark:text-emerald-400",
    hover: "hover:border-emerald-400 dark:hover:border-emerald-600",
  },
  medium: {
    bg: "bg-gradient-to-br from-blue-50 to-indigo-50 dark:from-blue-950/30 dark:to-indigo-950/30",
    border: "border-blue-200 dark:border-blue-800",
    accent: "text-blue-700 dark:text-blue-400",
    hover: "hover:border-blue-400 dark:hover:border-blue-600",
  },
  hard: {
    bg: "bg-gradient-to-br from-rose-50 to-pink-50 dark:from-rose-950/30 dark:to-pink-950/30",
    border: "border-rose-200 dark:border-rose-800",
    accent: "text-rose-700 dark:text-rose-400",
    hover: "hover:border-rose-400 dark:hover:border-rose-600",
  },
  custom: {
    bg: "bg-gradient-to-br from-violet-50 to-purple-50 dark:from-violet-950/30 dark:to-purple-950/30",
    border: "border-violet-200 dark:border-violet-800",
    accent: "text-violet-700 dark:text-violet-400",
    hover: "hover:border-violet-400 dark:hover:border-violet-600",
  },
}

export const LANGUAGE_DATA: Record<string, Flashcard[]> = {
  "en-vi": [
    { id: "1", front: "Hello", back: "Xin chào", difficulty: "easy" },
    { id: "2", front: "Thank you", back: "Cảm ơn", difficulty: "easy" },
    { id: "3", front: "Good morning", back: "Chào buổi sáng", difficulty: "medium" },
    { id: "4", front: "How are you?", back: "Bạn khỏe không?", difficulty: "medium" },
    { id: "5", front: "I love you", back: "Anh yêu em", difficulty: "easy" },
    { id: "6", front: "Goodbye", back: "Tạm biệt", difficulty: "easy" },
    { id: "7", front: "Please", back: "Làm ơn", difficulty: "easy" },
    { id: "8", front: "Excuse me", back: "Xin lỗi", difficulty: "medium" },
    { id: "9", front: "What is your name?", back: "Bạn tên là gì?", difficulty: "medium" },
    { id: "10", front: "Nice to meet you", back: "Rất vui được gặp bạn", difficulty: "hard" },
  ],
  "en-es": [
    { id: "1", front: "Hello", back: "Hola", difficulty: "easy" },
    { id: "2", front: "Thank you", back: "Gracias", difficulty: "easy" },
    { id: "3", front: "Good morning", back: "Buenos días", difficulty: "medium" },
    { id: "4", front: "How are you?", back: "¿Cómo estás?", difficulty: "medium" },
    { id: "5", front: "I love you", back: "Te amo", difficulty: "easy" },
    { id: "6", front: "Goodbye", back: "Adiós", difficulty: "easy" },
    { id: "7", front: "Please", back: "Por favor", difficulty: "easy" },
    { id: "8", front: "Excuse me", back: "Disculpe", difficulty: "medium" },
    { id: "9", front: "What is your name?", back: "¿Cómo te llamas?", difficulty: "medium" },
    { id: "10", front: "Nice to meet you", back: "Encantado de conocerte", difficulty: "hard" },
  ],
  "en-fr": [
    { id: "1", front: "Hello", back: "Bonjour", difficulty: "easy" },
    { id: "2", front: "Thank you", back: "Merci", difficulty: "easy" },
    { id: "3", front: "Good morning", back: "Bonjour", difficulty: "medium" },
    { id: "4", front: "How are you?", back: "Comment allez-vous?", difficulty: "medium" },
    { id: "5", front: "I love you", back: "Je t'aime", difficulty: "easy" },
    { id: "6", front: "Goodbye", back: "Au revoir", difficulty: "easy" },
    { id: "7", front: "Please", back: "S'il vous plaît", difficulty: "easy" },
    { id: "8", front: "Excuse me", back: "Excusez-moi", difficulty: "medium" },
    { id: "9", front: "What is your name?", back: "Comment vous appelez-vous?", difficulty: "medium" },
    { id: "10", front: "Nice to meet you", back: "Enchanté", difficulty: "hard" },
  ],
  "en-ja": [
    { id: "1", front: "Hello", back: "こんにちは", difficulty: "easy" },
    { id: "2", front: "Thank you", back: "ありがとう", difficulty: "easy" },
    { id: "3", front: "Good morning", back: "おはようございます", difficulty: "medium" },
    { id: "4", front: "How are you?", back: "元気ですか？", difficulty: "medium" },
    { id: "5", front: "I love you", back: "愛してる", difficulty: "easy" },
    { id: "6", front: "Goodbye", back: "さようなら", difficulty: "easy" },
    { id: "7", front: "Please", back: "お願いします", difficulty: "easy" },
    { id: "8", front: "Excuse me", back: "すみません", difficulty: "medium" },
    { id: "9", front: "What is your name?", back: "お名前は何ですか？", difficulty: "medium" },
    { id: "10", front: "Nice to meet you", back: "はじめまして", difficulty: "hard" },
  ],
  "en-zh": [
    { id: "1", front: "Hello", back: "你好", difficulty: "easy" },
    { id: "2", front: "Thank you", back: "谢谢", difficulty: "easy" },
    { id: "3", front: "Good morning", back: "早上好", difficulty: "medium" },
    { id: "4", front: "How are you?", back: "你好吗？", difficulty: "medium" },
    { id: "5", front: "I love you", back: "我爱你", difficulty: "easy" },
    { id: "6", front: "Goodbye", back: "再见", difficulty: "easy" },
    { id: "7", front: "Please", back: "请", difficulty: "easy" },
    { id: "8", front: "Excuse me", back: "对不起", difficulty: "medium" },
    { id: "9", front: "What is your name?", back: "你叫什么名字？", difficulty: "medium" },
    { id: "10", front: "Nice to meet you", back: "很高兴认识你", difficulty: "hard" },
  ],
  "en-ko": [
    { id: "1", front: "Hello", back: "안녕하세요", difficulty: "easy" },
    { id: "2", front: "Thank you", back: "감사합니다", difficulty: "easy" },
    { id: "3", front: "Good morning", back: "좋은 아침", difficulty: "medium" },
    { id: "4", front: "How are you?", back: "어떻게 지내세요?", difficulty: "medium" },
    { id: "5", front: "I love you", back: "사랑해요", difficulty: "easy" },
    { id: "6", front: "Goodbye", back: "안녕히 가세요", difficulty: "easy" },
    { id: "7", front: "Please", back: "부탁합니다", difficulty: "easy" },
    { id: "8", front: "Excuse me", back: "실례합니다", difficulty: "medium" },
    { id: "9", front: "What is your name?", back: "이름이 뭐예요?", difficulty: "medium" },
    { id: "10", front: "Nice to meet you", back: "만나서 반갑습니다", difficulty: "hard" },
  ],
}

export const LANGUAGES: Record<string, Language> = {
  en: { name: "English", speech: "en-US", flag: "🇺🇸" },
  vi: { name: "Tiếng Việt", speech: "vi-VN", flag: "🇻🇳" },
  es: { name: "Español", speech: "es-ES", flag: "🇪🇸" },
  fr: { name: "Français", speech: "fr-FR", flag: "🇫🇷" },
  ja: { name: "日本語", speech: "ja-JP", flag: "🇯🇵" },
  zh: { name: "中文", speech: "zh-CN", flag: "🇨🇳" },
  ko: { name: "한국어", speech: "ko-KR", flag: "🇰🇷" },
}

