import { User } from "./types"

export const users: User[] = [
    {
      id: 1,
      name: "Nguyễn Văn A",
      email: "nguyenvana@email.com",
      avatar: "/vietnamese-chef-male.jpg",
      role: "owner",
      joinDate: "01/01/2024",
      status: "active",
      phone: "+84 901 234 567",
      totalReviews: 45,
      totalFavorites: 23,
      lastActive: "2 giờ trước",
    },
    {
      id: 2,
      name: "Trần Thị B",
      email: "tranthib@email.com",
      avatar: "/vietnamese-woman-user.jpg",
      role: "user",
      joinDate: "15/01/2024",
      status: "active",
      phone: "+84 902 345 678",
      totalReviews: 12,
      totalFavorites: 8,
      lastActive: "1 ngày trước",
    },
    {
      id: 3,
      name: "Lê Văn C",
      email: "levanc@email.com",
      avatar: "/vietnamese-chef-male-2.jpg",
      role: "owner",
      joinDate: "20/02/2024",
      status: "suspended",
      phone: "+84 903 456 789",
      totalReviews: 0,
      totalFavorites: 0,
      lastActive: "1 tuần trước",
    },
    {
      id: 4,
      name: "Phạm Thị D",
      email: "phamthid@email.com",
      avatar: "/vietnamese-woman-user-2.jpg",
      role: "user",
      joinDate: "05/03/2024",
      status: "active",
      phone: "+84 904 567 890",
      totalReviews: 28,
      totalFavorites: 15,
      lastActive: "5 giờ trước",
    },
    {
      id: 5,
      name: "Hoàng Văn E",
      email: "hoangvane@email.com",
      avatar: "/vietnamese-chef-male-3.jpg",
      role: "admin",
      joinDate: "12/03/2024",
      status: "active",
      phone: "+84 905 678 901",
      totalReviews: 0,
      totalFavorites: 0,
      lastActive: "30 phút trước",
    },
  ]