import { Cake, ChefHat, Coffee, IceCream, Pizza, Soup, Utensils, } from "lucide-react"

    export   const categories = [
        { id: "all", name: "Tất cả", icon: Utensils, color: "from-purple-500 to-pink-500" },
        { id: "pho", name: "Phở", icon: Soup, color: "from-green-500 to-emerald-500" },
        { id: "banh-mi", name: "Bánh Mì", icon: Pizza, color: "from-orange-500 to-amber-500" },
        { id: "com-tam", name: "Cơm Tấm", icon: ChefHat, color: "from-blue-500 to-cyan-500" },
        { id: "coffee", name: "Cà Phê", icon: Coffee, color: "from-amber-700 to-yellow-600" },
        { id: "dessert", name: "Tráng Miệng", icon: IceCream, color: "from-pink-500 to-rose-500" },
        { id: "cake", name: "Bánh Ngọt", icon: Cake, color: "from-red-500 to-pink-500" },
    ]

  export  const recommendedRoutes = [
        {
            id: 1,
            name: "Tour Ẩm Thực Quận 1",
            duration: "3 giờ",
            stops: 5,
            distance: "2.5 km",
            rating: 4.9,
            image: "/img/pho-bowl.jpg",
            highlights: ["Phở Hòa", "Bánh Mì Huỳnh Hoa", "Cà Phê Apartment"],
            price: "Miễn phí",
        },
        {
            id: 2,
            name: "Khám Phá Món Bún",
            duration: "2 giờ",
            stops: 4,
            distance: "1.8 km",
            rating: 4.7,
            image: "/img/bun-bo-hue.png",
            highlights: ["Bún Bò Huế", "Bún Riêu", "Bún Thịt Nướng"],
            price: "Miễn phí",
        },
        {
            id: 3,
            name: "Chợ Đêm Ẩm Thực",
            duration: "4 giờ",
            stops: 8,
            distance: "3.2 km",
            rating: 4.8,
            image: "/img/com-tam-rice.jpg",
            highlights: ["Cơm Tấm", "Bánh Xèo", "Chè", "Ốc"],
            price: "Miễn phí",
        },
    ]

  export   const featuredRestaurants = [
        {
            id: 1,
            name: "Phở Hòa Pasteur",
            cuisine: "Phở",
            rating: 4.8,
            reviews: 1234,
            image: "/img/pho-bowl.jpg",
            district: "Quận 1",
            distance: "0.5 km",
            priceRange: "50-80k",
            isOpen: true,
            hasLive: true,
            hasAR: true,
        },
        {
            id: 2,
            name: "Bánh Mì Huỳnh Hoa",
            cuisine: "Bánh Mì",
            rating: 4.9,
            reviews: 2341,
            image: "/img/banh-mi-sandwich.jpg",
            district: "Quận 1",
            distance: "1.2 km",
            priceRange: "30-50k",
            isOpen: true,
            hasLive: false,
            hasAR: true,
        },
        {
            id: 3,
            name: "Cơm Tấm Mộc",
            cuisine: "Cơm Tấm",
            rating: 4.7,
            reviews: 876,
            image: "/img/com-tam-rice.jpg",
            district: "Quận 3",
            distance: "2.1 km",
            priceRange: "40-70k",
            isOpen: true,
            hasLive: true,
            hasAR: false,
        },
        {
            id: 4,
            name: "Bún Bò Huế Đông Ba",
            cuisine: "Bún",
            rating: 4.6,
            reviews: 654,
            image: "/img/bun-bo-hue.png",
            district: "Quận 5",
            distance: "3.5 km",
            priceRange: "45-65k",
            isOpen: false,
            hasLive: false,
            hasAR: true,
        },
    ]

    export const liveStreams = [
        {
            id: 1,
            title: "Nấu Phở Bò Truyền Thống",
            chef: "Chef Minh",
            viewers: 1234,
            thumbnail: "/img/pho-bowl.jpg",
            restaurant: "Phở Hòa Pasteur",
        },
        {
            id: 2,
            title: "Làm Bánh Mì Thập Cẩm",
            chef: "Chef Lan",
            viewers: 856,
            thumbnail: "/img/banh-mi-sandwich.jpg",
            restaurant: "Bánh Mì Huỳnh Hoa",
        },
        {
            id: 3,
            title: "Cơm Tấm Sườn Bì Chả",
            chef: "Chef Tuấn",
            viewers: 642,
            thumbnail: "/img/com-tam-rice.jpg",
            restaurant: "Cơm Tấm Mộc",
        },
    ]

   export  const upcomingEvents = [
        {
            id: 1,
            title: "Lớp Nấu Ăn: Phở Bò",
            date: "15/11/2024",
            time: "14:00",
            location: "Quận 1",
            participants: 12,
            maxParticipants: 20,
            price: "500k",
        },
        {
            id: 2,
            title: "Tour Ẩm Thực Đường Phố",
            date: "18/11/2024",
            time: "18:00",
            location: "Quận 5",
            participants: 8,
            maxParticipants: 15,
            price: "Miễn phí",
        },
        {
            id: 3,
            title: "Festival Bánh Mì Sài Gòn",
            date: "20/11/2024",
            time: "10:00",
            location: "Công viên 23/9",
            participants: 156,
            maxParticipants: 500,
            price: "50k",
        },
        {
            id: 4,
            title: "Festival Bánh Mì Sài Gòn",
            date: "20/11/2024",
            time: "10:00",
            location: "Công viên 23/9",
            participants: 156,
            maxParticipants: 500,
            price: "50k",
        },
    ]
